dist: xenial

branches:
  except:
    - master_xenial

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install qt5-default qt5-qmake
  - sudo apt-get install libqt5gstreamer-dev
  - sudo apt-get install libzmq3-dev
  - sudo apt-get install libprotobuf-dev protobuf-compiler
  - sudo apt-get install libyaml-dev libyaml-cpp-dev libboost-dev

script:
  - sh compile_msgs.sh
  - qmake
  - make

language: cpp
